version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_PUBLIC_URL=${MONGODB_URL} # URL de conexión a la base de datos
      - NODE_ENV=production # Configura el entorno de producción
    ports:
      - "5000:5000" # Exponer el puerto del backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge